### ISSUE TITLE
[ERROR  ] '_resolved_command_str' [jobs.py:show_oneline:102] (KeyError)

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reproman#492] opened 2019-12-04 20:39 UTC
```shell
$> git describe
v0.2.1-29-gb6d1973

$> reproman -l 2 jobs
2019-12-04 15:36:50,858 [ERROR  ] '_resolved_command_str' [jobs.py:show_oneline:102] (KeyError) 
2019-12-04 15:36:50,858 [Level 5] Exiting 
```
Ideally (besides making it more robust or puking with a dedicated error) there should also be some debug level message stating what files are read here about jobs status.  I guess I have some stale (incompatible) ones laying around but need to figure out where to look.

**Comment by kyleam** [comment] 2019-12-04 20:56
>  I guess I have some stale (incompatible) ones laying around

Yes, this is due to 8520c508a (ENH: run: Don't touch command_str spec value, 2019-09-30).

I personally don't think it is a good idea to add compatibility kludges for changes that were made while marked as beta.  Adding more debug messages is of course fine.

**Comment by yarikoptic** [comment] 2019-12-05 14:14
+1 for no compatibility kludges.  But may be worth adding "version" information into job specs, so later on would be possible to crash with "job spec X is of incompatible prior version Y, please remove and rerun" or alike.

**Comment by kyleam** [comment] 2019-12-05 14:20
> But may be worth adding "version" information into job specs, so later on would be possible to crash with "job spec X is of incompatible prior version Y, please remove and rerun" or alike.

Yeah, good point.  The specs *do* currently have a version (as of bfb5edbe6), but we could consider places where we could catch an exception and give a hint that maybe the old version spec is the cause.

**Comment by kyleam** [comment] 2020-05-26 17:56
I think what is done by gh-515 should be sufficient.

**Closed by kyleam** 2020-05-26 17:56 UTC
Labels: bug
